# Generated by Django 4.1.2 on 2022-11-27 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hostel_api.path_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер корпуса=")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=25, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=25, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=25, verbose_name="Отчество"),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("Бакалавр", "Бакалавр"),
                            ("Магистр", "Магистр"),
                            ("Аспирант", "Аспирант"),
                        ],
                        default="Бакалавр",
                        max_length=25,
                        verbose_name="Ступень обучения",
                    ),
                ),
                ("group", models.CharField(max_length=10, verbose_name="Группа")),
                (
                    "study_direction",
                    models.CharField(
                        max_length=50, verbose_name="Направление подготовки"
                    ),
                ),
                (
                    "student_card",
                    models.PositiveIntegerField(verbose_name="Номер студенческого"),
                ),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                ("enter_date", models.DateField(verbose_name="Дата зачисления")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=25, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=25, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=25, verbose_name="Отчество"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Номер комнаты")),
                (
                    "max_residents",
                    models.PositiveIntegerField(
                        verbose_name="Максимальное число жильцов"
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hostel_api.building",
                        verbose_name="Корпус",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        null=True,
                        upload_to=hostel_api.path_utils.get_photo_path,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "contract",
                    models.FileField(
                        null=True,
                        upload_to=hostel_api.path_utils.get_contract_path,
                        verbose_name="Договор",
                    ),
                ),
                (
                    "registration",
                    models.FileField(
                        null=True,
                        upload_to=hostel_api.path_utils.get_registration_path,
                        verbose_name="Временная регистрация",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="hostel_api.room",
                        verbose_name="Комната",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resident",
                        to="hostel_api.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="building",
            name="staff",
            field=models.ManyToManyField(
                related_name="buildings",
                to="hostel_api.staff",
                verbose_name="Комендант",
            ),
        ),
    ]
