# Generated by Django 4.1.2 on 2022-11-27 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hostel_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Описание"),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_seen",
                    models.BooleanField(default=False, verbose_name="Просмотрено"),
                ),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Заархивировано"),
                ),
                (
                    "is_provided",
                    models.BooleanField(default=False, verbose_name="Услуга оказана"),
                ),
                (
                    "provision_date",
                    models.DateField(null=True, verbose_name="Дата оказания услуги"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel_api.resident",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="requests",
                        to="hostel_api.staff",
                        verbose_name="Получатель",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовок")),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Описание"),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликовано"),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала отображения"),
                ),
                ("end_date", models.DateField(verbose_name="Дата конца отображения")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostel_api.staff",
                        verbose_name="Автор",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="notifications",
                        to="hostel_api.resident",
                        verbose_name="Получатели",
                    ),
                ),
            ],
        ),
    ]
